# Generated by Django 4.2 on 2023-05-18 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='finish',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 14, 30, 8, 558948)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 14, 30, 8, 558948)),
        ),
    ]
